#!/bin/bash

VERSION="v1.0.0"
NS_OPT=""

function cj_list () {
  mapfile -t cronjobs <<< `kubectl get cronjob $NS_OPT | grep -v '^NAME' | awk '{print $1}'`
  if [ -z "${cronjobs[0]}" ]; then
    echo "Exit"
    exit 1
  fi

  echo ""
  PS3="Select Job (or 'q' to quit)> "
  select CRONJOB in "${cronjobs[@]}"
  do
    if [ "${REPLY}" = "q" ]; then
        exit 0
    elif [ -n "$CRONJOB" ]; then
        break
    fi
  done
}

function show_usage () {
    echo ""
    echo "kubectl pick job version $VERSION"
    echo "  Usage:    kubectl pick job [options] [cronjob name>]"
    echo "  Options:"
    echo "            -n <namespace>   Specify namespace"
    echo "            -h               Show this usage"
    echo ""
    exit 1
}

set -eu

while getopts hn: OPT
do
    if [[ "$OPT" = - ]]; then
      OPT="$OPTARG"
    fi
    case $OPT in
        "h" ) show_usage ;;
        "n" ) NS_OPT="-n $OPTARG" ;;
    esac
done

shift $(expr $OPTIND - 1)

if [ $# -lt 1 ]; then
  cj_list
else
  CRONJOB=$1
fi
kubectl create job $CRONJOB-$(date +%s) $NS_OPT --from cronjob/$CRONJOB
